export const BASE_URL = process.env.REACT_APP_BACKEND_API;
export const CLOUDINARY_CLOUD_NAME =
  process.env.REACT_APP_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET =
  process.env.REACT_APP_CLOUDINARY_UPLOAD_PRESET;
export const EXERCISES_PER_PAGE = 31;
export const MEALS_PER_PAGE = 31;
